import { PropertyWithImages } from './propertyService';

export const dummyPropertiesForSale: PropertyWithImages[] = [
  {
    id: 'sale-1',
    title: 'Modern Luxury Condo in KLCC',
    description: 'Premium 3-bedroom condominium with stunning city views, high-end finishes, and world-class facilities. Perfect for executives and families.',
    property_type: 'condo',
    listing_type: 'sale',
    price: 1200000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1650,
    address: '168 Jalan Ampang, KLCC',
    city: 'Kuala Lumpur',
    state: 'KL',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Swimming Pool', 'Gym', 'Security 24/7', 'Covered Parking', 'Concierge', 'Sky Lounge', 'Jogging Track'],
    furnished: 'fully_furnished',
    availability_date: null,
    deposit_info: null,
    agent_id: 'agent-001',
    status: 'active',
    featured: true,
    views_count: 234,
    created_at: '2025-10-01T00:00:00Z',
    updated_at: '2025-10-01T00:00:00Z',
    property_images: [
      {
        id: 'sale-1-img-1',
        property_id: 'sale-1',
        image_url: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Condo exterior',
        display_order: 0,
        is_primary: true,
        created_at: '2025-10-01T00:00:00Z'
      },
      {
        id: 'sale-1-img-2',
        property_id: 'sale-1',
        image_url: 'https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Living room',
        display_order: 1,
        is_primary: false,
        created_at: '2025-10-01T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Ahmad Zaki',
      phone: '+60 12-345-6789',
      email: 'ahmad@klproperties.my',
      avatar_url: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'KL Premium Properties'
    }
  },
  {
    id: 'sale-2',
    title: 'Spacious Terrace House in Mont Kiara',
    description: 'Beautiful 4-bedroom terrace in exclusive Mont Kiara area. Spacious layout with private garden and modern renovations.',
    property_type: 'house',
    listing_type: 'sale',
    price: 1850000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2400,
    address: '23 Jalan Kiara 3, Mont Kiara',
    city: 'Kuala Lumpur',
    state: 'KL',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Garden', 'Parking', 'Near International School', 'Shopping Mall', 'Renovated Kitchen', 'Smart Home'],
    furnished: 'partially_furnished',
    availability_date: null,
    deposit_info: null,
    agent_id: 'agent-002',
    status: 'active',
    featured: true,
    views_count: 189,
    created_at: '2025-09-30T00:00:00Z',
    updated_at: '2025-09-30T00:00:00Z',
    property_images: [
      {
        id: 'sale-2-img-1',
        property_id: 'sale-2',
        image_url: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'House exterior',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-30T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Sarah Lee',
      phone: '+60 16-234-5678',
      email: 'sarah@montkiara.com',
      avatar_url: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Mont Kiara Realty'
    }
  },
  {
    id: 'sale-3',
    title: 'Premium Condo in Johor Bahru CIQ Area',
    description: 'Strategically located near CIQ checkpoint. Perfect for investment or own stay. Excellent rental yield potential.',
    property_type: 'condo',
    listing_type: 'sale',
    price: 580000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1050,
    address: 'Jalan Tun Abdul Razak, JB',
    city: 'Johor Bahru',
    state: 'Johor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Swimming Pool', 'Gym', 'Security', 'Near CIQ', 'Shopping Mall', 'Parking'],
    furnished: 'fully_furnished',
    availability_date: null,
    deposit_info: null,
    agent_id: 'agent-003',
    status: 'active',
    featured: true,
    views_count: 312,
    created_at: '2025-09-29T00:00:00Z',
    updated_at: '2025-09-29T00:00:00Z',
    property_images: [
      {
        id: 'sale-3-img-1',
        property_id: 'sale-3',
        image_url: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Condo view',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-29T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'David Tan',
      phone: '+60 17-345-6789',
      email: 'david@jbproperties.my',
      avatar_url: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'JB Investment Properties'
    }
  },
  {
    id: 'sale-4',
    title: 'Affordable Apartment in Taman Daya',
    description: 'Well-maintained 3-bedroom apartment in established neighborhood. Great for first-time buyers and families.',
    property_type: 'apartment',
    listing_type: 'sale',
    price: 350000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1100,
    address: 'Jalan Daya 12, Taman Daya',
    city: 'Johor Bahru',
    state: 'Johor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Playground', 'Security', 'Parking', 'Near School', 'Market Nearby'],
    furnished: 'unfurnished',
    availability_date: null,
    deposit_info: null,
    agent_id: 'agent-004',
    status: 'active',
    featured: false,
    views_count: 156,
    created_at: '2025-09-28T00:00:00Z',
    updated_at: '2025-09-28T00:00:00Z',
    property_images: [
      {
        id: 'sale-4-img-1',
        property_id: 'sale-4',
        image_url: 'https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Apartment interior',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-28T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Siti Nurhaliza',
      phone: '+60 13-456-7890',
      email: 'siti@dayahomes.com',
      avatar_url: 'https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Daya Homes Agency'
    }
  },
  {
    id: 'sale-5',
    title: 'Luxury Villa in Setia Eco Gardens',
    description: 'Stunning 5-bedroom villa with private pool in prestigious gated community. Perfect for affluent families.',
    property_type: 'villa',
    listing_type: 'sale',
    price: 2800000,
    bedrooms: 5,
    bathrooms: 4,
    sqft: 4200,
    address: 'Setia Eco Gardens, Gelang Patah',
    city: 'Johor Bahru',
    state: 'Johor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Private Pool', 'Garden', 'Security 24/7', 'Clubhouse', 'Maid Room', 'Double Garage', 'Smart Home'],
    furnished: 'partially_furnished',
    availability_date: null,
    deposit_info: null,
    agent_id: 'agent-005',
    status: 'active',
    featured: true,
    views_count: 278,
    created_at: '2025-09-27T00:00:00Z',
    updated_at: '2025-09-27T00:00:00Z',
    property_images: [
      {
        id: 'sale-5-img-1',
        property_id: 'sale-5',
        image_url: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Villa exterior',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-27T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Michael Wong',
      phone: '+60 12-567-8901',
      email: 'michael@luxurysetia.my',
      avatar_url: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Luxury Setia Properties'
    }
  },
  {
    id: 'sale-6',
    title: 'Semi-Detached House in Taman Molek',
    description: 'Spacious 4-bedroom semi-D with renovation potential. Great location near schools and amenities.',
    property_type: 'house',
    listing_type: 'sale',
    price: 720000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2200,
    address: 'Jalan Molek 1/8, Taman Molek',
    city: 'Johor Bahru',
    state: 'Johor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Garden', 'Parking', 'Near International School', 'Shopping Complex', 'Established Area'],
    furnished: 'unfurnished',
    availability_date: null,
    deposit_info: null,
    agent_id: 'agent-006',
    status: 'active',
    featured: false,
    views_count: 145,
    created_at: '2025-09-26T00:00:00Z',
    updated_at: '2025-09-26T00:00:00Z',
    property_images: [
      {
        id: 'sale-6-img-1',
        property_id: 'sale-6',
        image_url: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Semi-D house',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-26T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Lisa Chong',
      phone: '+60 16-678-9012',
      email: 'lisa@molekproperties.com',
      avatar_url: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Molek Properties'
    }
  },
  {
    id: 'sale-7',
    title: 'Penang Heritage Shophouse',
    description: 'Rare heritage shophouse in Georgetown UNESCO area. Perfect for business or restoration project.',
    property_type: 'house',
    listing_type: 'sale',
    price: 1500000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1800,
    address: 'Lebuh Armenian, Georgetown',
    city: 'Georgetown',
    state: 'Penang',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Heritage Building', 'Commercial License', 'Tourist Area', 'Near UNESCO Sites', 'High Ceiling'],
    furnished: 'unfurnished',
    availability_date: null,
    deposit_info: null,
    agent_id: 'agent-007',
    status: 'active',
    featured: true,
    views_count: 198,
    created_at: '2025-09-25T00:00:00Z',
    updated_at: '2025-09-25T00:00:00Z',
    property_images: [
      {
        id: 'sale-7-img-1',
        property_id: 'sale-7',
        image_url: 'https://images.pexels.com/photos/1115804/pexels-photo-1115804.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Shophouse exterior',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-25T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Lim Wei Chuan',
      phone: '+60 14-789-0123',
      email: 'lim@penangheritage.my',
      avatar_url: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Penang Heritage Properties'
    }
  },
  {
    id: 'sale-8',
    title: 'Studio Apartment in Bangsar South',
    description: 'Compact and efficient studio perfect for young professionals. Walking distance to LRT station.',
    property_type: 'studio',
    listing_type: 'sale',
    price: 380000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 550,
    address: 'Jalan Kerinchi, Bangsar South',
    city: 'Kuala Lumpur',
    state: 'KL',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Near LRT', 'Swimming Pool', 'Gym', 'Security', 'Cafes Nearby', 'Co-working Space'],
    furnished: 'fully_furnished',
    availability_date: null,
    deposit_info: null,
    agent_id: 'agent-008',
    status: 'active',
    featured: false,
    views_count: 223,
    created_at: '2025-09-24T00:00:00Z',
    updated_at: '2025-09-24T00:00:00Z',
    property_images: [
      {
        id: 'sale-8-img-1',
        property_id: 'sale-8',
        image_url: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Studio interior',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-24T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Kevin Ng',
      phone: '+60 19-890-1234',
      email: 'kevin@bangsarstudios.com',
      avatar_url: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Bangsar Studios'
    }
  },
  {
    id: 'sale-9',
    title: 'Executive Condo in Cyberjaya',
    description: 'Modern 3-bedroom executive condo in tech hub. Smart home features and excellent facilities.',
    property_type: 'condo',
    listing_type: 'sale',
    price: 650000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1350,
    address: 'Persiaran Apec, Cyberjaya',
    city: 'Cyberjaya',
    state: 'Selangor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Smart Home', 'High Speed Internet', 'Swimming Pool', 'Gym', 'Study Room', 'Green Building'],
    furnished: 'partially_furnished',
    availability_date: null,
    deposit_info: null,
    agent_id: 'agent-009',
    status: 'active',
    featured: false,
    views_count: 187,
    created_at: '2025-09-23T00:00:00Z',
    updated_at: '2025-09-23T00:00:00Z',
    property_images: [
      {
        id: 'sale-9-img-1',
        property_id: 'sale-9',
        image_url: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Executive condo',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-23T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Rachel Koh',
      phone: '+60 13-901-2345',
      email: 'rachel@cyberjayahomes.my',
      avatar_url: 'https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Cyberjaya Homes'
    }
  },
  {
    id: 'sale-10',
    title: 'Bungalow in Shah Alam',
    description: 'Prestigious corner lot bungalow with swimming pool. Perfect for large families seeking luxury and space.',
    property_type: 'house',
    listing_type: 'sale',
    price: 3200000,
    bedrooms: 6,
    bathrooms: 5,
    sqft: 5500,
    address: 'Seksyen 7, Shah Alam',
    city: 'Shah Alam',
    state: 'Selangor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Swimming Pool', 'Garden', 'Maid Room', 'Study Room', 'Wine Cellar', 'Smart Home', 'Triple Garage'],
    furnished: 'partially_furnished',
    availability_date: null,
    deposit_info: null,
    agent_id: 'agent-010',
    status: 'active',
    featured: true,
    views_count: 301,
    created_at: '2025-09-22T00:00:00Z',
    updated_at: '2025-09-22T00:00:00Z',
    property_images: [
      {
        id: 'sale-10-img-1',
        property_id: 'sale-10',
        image_url: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Bungalow exterior',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-22T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Dr. Azmi Hassan',
      phone: '+60 12-012-3456',
      email: 'azmi@shahalampremium.my',
      avatar_url: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Shah Alam Premium Properties'
    }
  }
];

export const dummyPropertiesForRent: PropertyWithImages[] = [
  {
    id: 'rent-1',
    title: 'Luxury 3BR Condo for Rent - Sutera Avenue',
    description: 'Stunning fully furnished 3-bedroom with city views. Perfect for executives and expats. Available immediately.',
    property_type: 'condo',
    listing_type: 'rent',
    price: 3200,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1400,
    address: 'Jalan Sutera Tanjung 8/4, Sutera Utama',
    city: 'Johor Bahru',
    state: 'Johor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['City View', 'Infinity Pool', 'Gym', 'Security 24/7', 'Near CIQ', 'Shopping Mall', 'Covered Parking'],
    furnished: 'fully_furnished',
    availability_date: '2025-10-15',
    deposit_info: '2 months + 1 month advance + utilities deposit',
    agent_id: 'agent-011',
    status: 'active',
    featured: true,
    views_count: 267,
    created_at: '2025-10-02T00:00:00Z',
    updated_at: '2025-10-02T00:00:00Z',
    property_images: [
      {
        id: 'rent-1-img-1',
        property_id: 'rent-1',
        image_url: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Luxury condo',
        display_order: 0,
        is_primary: true,
        created_at: '2025-10-02T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Jennifer Lim',
      phone: '+60 17-123-4567',
      email: 'jennifer@suterarentals.com',
      avatar_url: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Sutera Luxury Rentals'
    }
  },
  {
    id: 'rent-2',
    title: 'Cozy Studio for Rent - City Square Area',
    description: 'Affordable fully furnished studio in JB city center. Perfect for students and young professionals.',
    property_type: 'studio',
    listing_type: 'rent',
    price: 1200,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 550,
    address: 'Jalan Wong Ah Fook, JB',
    city: 'Johor Bahru',
    state: 'Johor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['City Center', 'Near Mall', 'Public Transport', 'Restaurants', 'WiFi Included', 'Laundry'],
    furnished: 'fully_furnished',
    availability_date: '2025-10-10',
    deposit_info: '2 months + 1 month advance',
    agent_id: 'agent-012',
    status: 'active',
    featured: false,
    views_count: 189,
    created_at: '2025-10-01T00:00:00Z',
    updated_at: '2025-10-01T00:00:00Z',
    property_images: [
      {
        id: 'rent-2-img-1',
        property_id: 'rent-2',
        image_url: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Studio apartment',
        display_order: 0,
        is_primary: true,
        created_at: '2025-10-01T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Sarah Ahmad',
      phone: '+60 13-234-5678',
      email: 'sarah@cityrentals.my',
      avatar_url: 'https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'City Square Rentals'
    }
  },
  {
    id: 'rent-3',
    title: 'Spacious 2BR Apartment - Taman Molek',
    description: 'Family-friendly apartment near international schools. Quiet neighborhood with good facilities.',
    property_type: 'apartment',
    listing_type: 'rent',
    price: 1800,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    address: 'Jalan Molek 1/6, Taman Molek',
    city: 'Johor Bahru',
    state: 'Johor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Swimming Pool', 'Playground', 'Security', 'Near International School', 'Shopping Complex', 'Parking'],
    furnished: 'partially_furnished',
    availability_date: '2025-10-20',
    deposit_info: '2 months + 1 month advance + utilities deposit',
    agent_id: 'agent-013',
    status: 'active',
    featured: false,
    views_count: 156,
    created_at: '2025-09-30T00:00:00Z',
    updated_at: '2025-09-30T00:00:00Z',
    property_images: [
      {
        id: 'rent-3-img-1',
        property_id: 'rent-3',
        image_url: 'https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Apartment living room',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-30T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Michelle Chen',
      phone: '+60 16-345-6789',
      email: 'michelle@molekrentals.com',
      avatar_url: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Molek Family Rentals'
    }
  },
  {
    id: 'rent-4',
    title: 'Budget Room for Rent - Skudai University Area',
    description: 'Single room perfect for students. Near UTM and universities. Utilities included.',
    property_type: 'apartment',
    listing_type: 'rent',
    price: 600,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 300,
    address: 'Taman Universiti, Skudai',
    city: 'Johor Bahru',
    state: 'Johor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Near University', 'Student Area', 'Food Courts', 'Public Transport', 'WiFi Included', 'Utilities Included'],
    furnished: 'fully_furnished',
    availability_date: '2025-10-05',
    deposit_info: '1 month + 1 month advance',
    agent_id: 'agent-014',
    status: 'active',
    featured: false,
    views_count: 234,
    created_at: '2025-09-29T00:00:00Z',
    updated_at: '2025-09-29T00:00:00Z',
    property_images: [
      {
        id: 'rent-4-img-1',
        property_id: 'rent-4',
        image_url: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Student room',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-29T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Kumar Raj',
      phone: '+60 19-456-7890',
      email: 'kumar@studentrentals.my',
      avatar_url: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Student Accommodations'
    }
  },
  {
    id: 'rent-5',
    title: 'Executive Penthouse - Mount Austin',
    description: 'Luxurious 4-bedroom penthouse with panoramic city views. Premium facilities and exclusive living.',
    property_type: 'condo',
    listing_type: 'rent',
    price: 4500,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2200,
    address: 'Jalan Mutiara Emas 9/23, Mount Austin',
    city: 'Johor Bahru',
    state: 'Johor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['City View', 'Private Balcony', 'Clubhouse', 'Security 24/7', 'Swimming Pool', 'Gym', 'Jacuzzi'],
    furnished: 'fully_furnished',
    availability_date: '2025-11-01',
    deposit_info: '3 months + 1 month advance + utilities deposit',
    agent_id: 'agent-015',
    status: 'active',
    featured: true,
    views_count: 298,
    created_at: '2025-09-28T00:00:00Z',
    updated_at: '2025-09-28T00:00:00Z',
    property_images: [
      {
        id: 'rent-5-img-1',
        property_id: 'rent-5',
        image_url: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Penthouse view',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-28T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'James Lim',
      phone: '+60 12-567-8901',
      email: 'james@mountaustinlux.com',
      avatar_url: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Mount Austin Luxury'
    }
  },
  {
    id: 'rent-6',
    title: 'Family House for Rent - Taman Daya',
    description: '4-bedroom double-storey terrace perfect for families. Near schools and amenities.',
    property_type: 'house',
    listing_type: 'rent',
    price: 2200,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2000,
    address: 'Jalan Daya 15, Taman Daya',
    city: 'Johor Bahru',
    state: 'Johor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Garden', 'Parking', 'Near Schools', 'Playground', 'Established Area', 'Market Nearby'],
    furnished: 'unfurnished',
    availability_date: '2025-10-25',
    deposit_info: '2 months + 1 month advance + utilities deposit',
    agent_id: 'agent-016',
    status: 'active',
    featured: false,
    views_count: 178,
    created_at: '2025-09-27T00:00:00Z',
    updated_at: '2025-09-27T00:00:00Z',
    property_images: [
      {
        id: 'rent-6-img-1',
        property_id: 'rent-6',
        image_url: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Terrace house',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-27T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'David Wong',
      phone: '+60 17-678-9012',
      email: 'david@dayafamily.com',
      avatar_url: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Daya Family Homes'
    }
  },
  {
    id: 'rent-7',
    title: 'Modern Serviced Apartment - Paradigm Area',
    description: 'Fully serviced 2-bedroom near Paradigm Mall. Housekeeping included. Perfect for professionals.',
    property_type: 'condo',
    listing_type: 'rent',
    price: 2800,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1000,
    address: 'Jalan Skudai, Near Paradigm Mall',
    city: 'Johor Bahru',
    state: 'Johor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Near Mall', 'Housekeeping Included', 'High Speed Internet', 'Near University', 'Gym', 'Security 24/7'],
    furnished: 'fully_furnished',
    availability_date: '2025-10-12',
    deposit_info: '2 months + 1 month advance',
    agent_id: 'agent-017',
    status: 'active',
    featured: false,
    views_count: 201,
    created_at: '2025-09-26T00:00:00Z',
    updated_at: '2025-09-26T00:00:00Z',
    property_images: [
      {
        id: 'rent-7-img-1',
        property_id: 'rent-7',
        image_url: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Serviced apartment',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-26T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Lisa Tan',
      phone: '+60 13-789-0123',
      email: 'lisa@paradigmserviced.com',
      avatar_url: 'https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Paradigm Serviced Residences'
    }
  },
  {
    id: 'rent-8',
    title: 'Shared House for Rent - Petaling Jaya',
    description: 'Comfortable room in shared house. Common facilities. Great for students and young professionals.',
    property_type: 'house',
    listing_type: 'rent',
    price: 800,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 400,
    address: 'SS2, Petaling Jaya',
    city: 'Petaling Jaya',
    state: 'Selangor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Shared Kitchen', 'WiFi', 'Parking', 'Near LRT', 'Laundry', 'Common Area'],
    furnished: 'fully_furnished',
    availability_date: '2025-10-08',
    deposit_info: '1 month + 1 month advance',
    agent_id: 'agent-018',
    status: 'active',
    featured: false,
    views_count: 167,
    created_at: '2025-09-25T00:00:00Z',
    updated_at: '2025-09-25T00:00:00Z',
    property_images: [
      {
        id: 'rent-8-img-1',
        property_id: 'rent-8',
        image_url: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Shared house room',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-25T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Amy Ng',
      phone: '+60 19-890-1234',
      email: 'amy@sharedliving.my',
      avatar_url: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'PJ Shared Living'
    }
  },
  {
    id: 'rent-9',
    title: 'Beachfront Condo for Rent - Penang',
    description: 'Stunning 2-bedroom with direct beach access. Resort-style living with amazing sea views.',
    property_type: 'condo',
    listing_type: 'rent',
    price: 3200,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    address: 'Batu Ferringhi, Penang',
    city: 'Georgetown',
    state: 'Penang',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Beach Access', 'Sea View', 'Swimming Pool', 'Restaurant', 'Spa', 'Water Sports', 'Security 24/7'],
    furnished: 'fully_furnished',
    availability_date: '2025-11-05',
    deposit_info: '2 months + 1 month advance + utilities deposit',
    agent_id: 'agent-019',
    status: 'active',
    featured: true,
    views_count: 312,
    created_at: '2025-09-24T00:00:00Z',
    updated_at: '2025-09-24T00:00:00Z',
    property_images: [
      {
        id: 'rent-9-img-1',
        property_id: 'rent-9',
        image_url: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Beachfront condo',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-24T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Peter Loh',
      phone: '+60 12-901-2345',
      email: 'peter@penangbeach.my',
      avatar_url: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Penang Beach Rentals'
    }
  },
  {
    id: 'rent-10',
    title: 'Executive Condo - Horizon Hills',
    description: 'Premium 3-bedroom in exclusive golf resort community. Perfect for families and executives.',
    property_type: 'condo',
    listing_type: 'rent',
    price: 3800,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1600,
    address: 'Horizon Hills, Nusajaya',
    city: 'Johor Bahru',
    state: 'Johor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Golf Course View', 'Resort Facilities', 'Swimming Pool', 'Tennis Court', 'Security 24/7', 'Clubhouse'],
    furnished: 'fully_furnished',
    availability_date: '2025-10-30',
    deposit_info: '3 months + 1 month advance + utilities deposit',
    agent_id: 'agent-020',
    status: 'active',
    featured: true,
    views_count: 245,
    created_at: '2025-09-23T00:00:00Z',
    updated_at: '2025-09-23T00:00:00Z',
    property_images: [
      {
        id: 'rent-10-img-1',
        property_id: 'rent-10',
        image_url: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Horizon Hills condo',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-23T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Daniel Tan',
      phone: '+60 16-012-3456',
      email: 'daniel@horizonrentals.com',
      avatar_url: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Horizon Hills Rentals'
    }
  }
];

export const dummyNewDevelopments: PropertyWithImages[] = [
  {
    id: 'new-1',
    title: 'The Peak Residences - KLCC New Launch',
    description: 'Ultra-luxury new development in prime KLCC location. Premium finishes, smart home technology, and world-class facilities. Launch promotion available.',
    property_type: 'condo',
    listing_type: 'sale',
    price: 1500000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1750,
    address: 'Jalan Ampang, KLCC',
    city: 'Kuala Lumpur',
    state: 'KL',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Sky Lounge', 'Infinity Pool', 'Smart Home', 'Concierge', 'Private Lift', 'Sky Garden', 'Gym', 'Security 24/7'],
    furnished: 'unfurnished',
    availability_date: '2026-06-01',
    deposit_info: 'Booking fee RM30,000',
    agent_id: 'agent-021',
    status: 'active',
    featured: true,
    views_count: 456,
    created_at: '2025-10-03T00:00:00Z',
    updated_at: '2025-10-03T00:00:00Z',
    property_images: [
      {
        id: 'new-1-img-1',
        property_id: 'new-1',
        image_url: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'The Peak artist impression',
        display_order: 0,
        is_primary: true,
        created_at: '2025-10-03T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Emily Tan',
      phone: '+60 12-222-3333',
      email: 'emily@thepeakklcc.my',
      avatar_url: 'https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Peak Development Group'
    }
  },
  {
    id: 'new-2',
    title: 'Medini Lakeside Residences - New Launch',
    description: 'Freehold lakeside condominium in Iskandar Malaysia. Integrated township with excellent ROI potential. Early bird discount available.',
    property_type: 'condo',
    listing_type: 'sale',
    price: 520000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 950,
    address: 'Medini, Iskandar Puteri',
    city: 'Johor Bahru',
    state: 'Johor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Lake View', 'Swimming Pool', 'Gym', 'Playground', 'Jogging Track', 'Retail Shops', 'Near Legoland'],
    furnished: 'unfurnished',
    availability_date: '2026-03-01',
    deposit_info: 'Booking fee RM5,000',
    agent_id: 'agent-022',
    status: 'active',
    featured: true,
    views_count: 389,
    created_at: '2025-10-02T00:00:00Z',
    updated_at: '2025-10-02T00:00:00Z',
    property_images: [
      {
        id: 'new-2-img-1',
        property_id: 'new-2',
        image_url: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Medini Lakeside',
        display_order: 0,
        is_primary: true,
        created_at: '2025-10-02T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Richard Lee',
      phone: '+60 17-333-4444',
      email: 'richard@medinilakeside.com',
      avatar_url: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Iskandar Properties'
    }
  },
  {
    id: 'new-3',
    title: 'Green Valley Eco Villas - Freehold',
    description: 'Exclusive freehold eco villas in Kajang. Green building certified. Limited units available with launch rebates.',
    property_type: 'villa',
    listing_type: 'sale',
    price: 1800000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3200,
    address: 'Kajang Hill, Kajang',
    city: 'Kajang',
    state: 'Selangor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Green Building', 'Solar Panels', 'Rainwater Harvesting', 'Garden', 'Smart Home', 'Security 24/7', 'Clubhouse'],
    furnished: 'unfurnished',
    availability_date: '2026-09-01',
    deposit_info: 'Booking fee RM20,000',
    agent_id: 'agent-023',
    status: 'active',
    featured: true,
    views_count: 278,
    created_at: '2025-10-01T00:00:00Z',
    updated_at: '2025-10-01T00:00:00Z',
    property_images: [
      {
        id: 'new-3-img-1',
        property_id: 'new-3',
        image_url: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Eco villa',
        display_order: 0,
        is_primary: true,
        created_at: '2025-10-01T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Dr. Azlan Ibrahim',
      phone: '+60 13-444-5555',
      email: 'azlan@greenvalley.my',
      avatar_url: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Green Valley Development'
    }
  },
  {
    id: 'new-4',
    title: 'Cyber Heights Residences - Smart Living',
    description: 'New smart living development in Cyberjaya. High-speed fiber internet, smart home features. Perfect for tech professionals.',
    property_type: 'condo',
    listing_type: 'sale',
    price: 680000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1300,
    address: 'Persiaran Bestari, Cyberjaya',
    city: 'Cyberjaya',
    state: 'Selangor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Smart Home', 'Fiber Internet 1Gbps', 'Co-working Space', 'Gym', 'Swimming Pool', 'EV Charging', 'Green Building'],
    furnished: 'unfurnished',
    availability_date: '2026-05-01',
    deposit_info: 'Booking fee RM10,000',
    agent_id: 'agent-024',
    status: 'active',
    featured: false,
    views_count: 234,
    created_at: '2025-09-30T00:00:00Z',
    updated_at: '2025-09-30T00:00:00Z',
    property_images: [
      {
        id: 'new-4-img-1',
        property_id: 'new-4',
        image_url: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Cyber Heights',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-30T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Jessica Wong',
      phone: '+60 19-555-6666',
      email: 'jessica@cyberheights.my',
      avatar_url: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Cyberjaya Smart Homes'
    }
  },
  {
    id: 'new-5',
    title: 'Ocean Pearl Residences - Penang Waterfront',
    description: 'Luxurious waterfront development in Penang. Unblocked sea views, resort-style facilities. Limited seafacing units.',
    property_type: 'condo',
    listing_type: 'sale',
    price: 1200000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1550,
    address: 'Tanjung Tokong, Penang',
    city: 'Georgetown',
    state: 'Penang',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Sea View', 'Infinity Pool', 'Beach Access', 'Gym', 'Sky Lounge', 'Concierge', 'Security 24/7'],
    furnished: 'unfurnished',
    availability_date: '2026-08-01',
    deposit_info: 'Booking fee RM25,000',
    agent_id: 'agent-025',
    status: 'active',
    featured: true,
    views_count: 401,
    created_at: '2025-09-29T00:00:00Z',
    updated_at: '2025-09-29T00:00:00Z',
    property_images: [
      {
        id: 'new-5-img-1',
        property_id: 'new-5',
        image_url: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Ocean Pearl',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-29T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Catherine Lim',
      phone: '+60 14-666-7777',
      email: 'catherine@oceanpearl.my',
      avatar_url: 'https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Ocean Pearl Development'
    }
  },
  {
    id: 'new-6',
    title: 'Bangsar Hill Park Residences',
    description: 'Premium hill-side development in Bangsar. Exclusive gated community with panoramic KL skyline views.',
    property_type: 'condo',
    listing_type: 'sale',
    price: 1650000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 1950,
    address: 'Jalan Bangsar, Bangsar',
    city: 'Kuala Lumpur',
    state: 'KL',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['City View', 'Infinity Pool', 'Gym', 'Sky Lounge', 'Yoga Deck', 'Wine Cellar', 'Concierge', 'Private Lift'],
    furnished: 'unfurnished',
    availability_date: '2026-07-01',
    deposit_info: 'Booking fee RM35,000',
    agent_id: 'agent-026',
    status: 'active',
    featured: true,
    views_count: 367,
    created_at: '2025-09-28T00:00:00Z',
    updated_at: '2025-09-28T00:00:00Z',
    property_images: [
      {
        id: 'new-6-img-1',
        property_id: 'new-6',
        image_url: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Bangsar Hill Park',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-28T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Robert Chen',
      phone: '+60 12-777-8888',
      email: 'robert@bangsarhill.my',
      avatar_url: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Bangsar Premium Developments'
    }
  },
  {
    id: 'new-7',
    title: 'Forest City Marina Suites - Waterfront Living',
    description: 'International waterfront development with Malaysia-Singapore connectivity. Tax incentives for foreign buyers.',
    property_type: 'condo',
    listing_type: 'sale',
    price: 850000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1150,
    address: 'Forest City, Gelang Patah',
    city: 'Johor Bahru',
    state: 'Johor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Marina View', 'Beach Access', 'International School', 'Golf Course', 'Shopping Mall', 'Medical Center', 'Security 24/7'],
    furnished: 'partially_furnished',
    availability_date: '2026-04-01',
    deposit_info: 'Booking fee RM15,000',
    agent_id: 'agent-027',
    status: 'active',
    featured: false,
    views_count: 312,
    created_at: '2025-09-27T00:00:00Z',
    updated_at: '2025-09-27T00:00:00Z',
    property_images: [
      {
        id: 'new-7-img-1',
        property_id: 'new-7',
        image_url: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Forest City Marina',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-27T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Steven Tan',
      phone: '+60 16-888-9999',
      email: 'steven@forestcitymarina.com',
      avatar_url: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Forest City Properties'
    }
  },
  {
    id: 'new-8',
    title: 'Setia Sky Residences - Affordable Luxury',
    description: 'Affordable new launch in established Setia Alam township. Complete facilities and easy highway access.',
    property_type: 'condo',
    listing_type: 'sale',
    price: 450000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1100,
    address: 'Persiaran Setia Dagang, Setia Alam',
    city: 'Shah Alam',
    state: 'Selangor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Swimming Pool', 'Gym', 'Playground', 'Jogging Track', 'Retail Shops', 'Security 24/7', 'Covered Parking'],
    furnished: 'unfurnished',
    availability_date: '2026-02-01',
    deposit_info: 'Booking fee RM5,000',
    agent_id: 'agent-028',
    status: 'active',
    featured: false,
    views_count: 289,
    created_at: '2025-09-26T00:00:00Z',
    updated_at: '2025-09-26T00:00:00Z',
    property_images: [
      {
        id: 'new-8-img-1',
        property_id: 'new-8',
        image_url: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Setia Sky',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-26T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Amanda Ng',
      phone: '+60 19-999-0000',
      email: 'amanda@setiasky.my',
      avatar_url: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Setia Development Group'
    }
  },
  {
    id: 'new-9',
    title: 'Tropicana Gardens - Integrated Living',
    description: 'Mixed development with retail podium. Walk to LRT station. Prime Kota Damansara location.',
    property_type: 'condo',
    listing_type: 'sale',
    price: 980000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1280,
    address: 'Jalan PJU 3, Kota Damansara',
    city: 'Petaling Jaya',
    state: 'Selangor',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Near LRT', 'Shopping Podium', 'Swimming Pool', 'Gym', 'Sky Garden', 'Security 24/7', 'Parking'],
    furnished: 'unfurnished',
    availability_date: '2026-06-01',
    deposit_info: 'Booking fee RM15,000',
    agent_id: 'agent-029',
    status: 'active',
    featured: false,
    views_count: 256,
    created_at: '2025-09-25T00:00:00Z',
    updated_at: '2025-09-25T00:00:00Z',
    property_images: [
      {
        id: 'new-9-img-1',
        property_id: 'new-9',
        image_url: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Tropicana Gardens',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-25T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Marcus Lim',
      phone: '+60 13-000-1111',
      email: 'marcus@tropicanagardens.my',
      avatar_url: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Tropicana Corporation'
    }
  },
  {
    id: 'new-10',
    title: 'Bukit Bintang City Centre - Premium Serviced Suites',
    description: 'Ultra-prime location in KL Golden Triangle. Hotel-operated serviced suites with guaranteed returns.',
    property_type: 'condo',
    listing_type: 'sale',
    price: 1350000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 950,
    address: 'Jalan Bukit Bintang, KL',
    city: 'Kuala Lumpur',
    state: 'KL',
    country: 'Malaysia',
    latitude: null,
    longitude: null,
    amenities: ['Hotel Operated', 'Guaranteed Returns', 'Concierge', 'Housekeeping', 'Swimming Pool', 'Gym', 'Sky Bar', 'Prime Location'],
    furnished: 'fully_furnished',
    availability_date: '2026-10-01',
    deposit_info: 'Booking fee RM30,000',
    agent_id: 'agent-030',
    status: 'active',
    featured: true,
    views_count: 478,
    created_at: '2025-09-24T00:00:00Z',
    updated_at: '2025-09-24T00:00:00Z',
    property_images: [
      {
        id: 'new-10-img-1',
        property_id: 'new-10',
        image_url: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt_text: 'Bukit Bintang City Centre',
        display_order: 0,
        is_primary: true,
        created_at: '2025-09-24T00:00:00Z'
      }
    ],
    profiles: {
      full_name: 'Dr. Patricia Wong',
      phone: '+60 12-111-2222',
      email: 'patricia@bbcitycentre.my',
      avatar_url: 'https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=150',
      company: 'Bukit Bintang Premier'
    }
  }
];

export const getAllDummyProperties = (): PropertyWithImages[] => {
  return [...dummyPropertiesForSale, ...dummyPropertiesForRent, ...dummyNewDevelopments];
};
